### ISSUE TITLE
Locally Fails Bootstrap/Install - Error: Modules Missing: Venv, Selenium

### ISSUE THREAD

**Issue by ajwinn** [get-salt-AI/SaltAI_Language_Toolkit#9]
Venv, Selenium, and Llama-Index-Readers-Web are installed...
```
pip freeze | findstr virtualenv
> virtualenv==20.21.0

pip freeze | findstr selenium
> selenium==4.23.1

pip freeze | findstr llama
> llama-index-core==0.10.62
> llama-index-readers-web==0.1.23
```

However, bootstrap process seems to say modules are not found.

```
Traceback (most recent call last):
  File "D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\modules\node_importer.py", line 20, in import_module
    module = importlib.import_module(module_name, package=package_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\image\website_screenshot.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
Import times for Salt AI Node Modules:
   0.0 seconds: D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\api\stability_ai.py
   0.1 seconds: D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\image\image_processing.py
   0.0 seconds: D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\image\loaders.py
   0.0 seconds (IMPORT FAILED): image\website_screenshot.py
Error: No module named 'selenium'
   0.0 seconds: D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\io\input_output.py
   0.0 seconds: D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\masking\clipseg.py
   0.0 seconds: D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\masking\cropping.py
   0.0 seconds: D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\masking\mask_convert.py
   0.0 seconds: D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\masking\mask_filters.py
   0.0 seconds: D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\string\processing.py
   0.0 seconds: D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\utility\convert.py
   0.0 seconds: D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI\nodes\utility\displayany.py

Loaded Nodes:
SaltAIStableVideoDiffusion [Stable Video Diffusion], SaltRGBAFromMask [Mask with Alpha (Transparency)], SaltImageBlendingModes [Composite Images], SaltLoadImageZip [Load Images from ZIP], SaltInput [Salt Workflow Input], SaltOutput [Salt Workflow Output], SaltInfo [Salt Workflow Info], SaltCLIPSegLoader [CLIPSeg Model Loader (Salt)], SaltCLIPSegMasking [Batch Image CLIPSeg Masking], SaltCropImageLocation [Crop Batch Image Location], SaltImagePasteCrop [Crop Batch Image Paste], SaltMaskCropRegion [Mask Batch Crop Region], SaltBatchCropDataExtractor [Extract Crop Data from Batch], SaltMasksToImages [Masks to Tensors], SaltMaskDominantRegion [Dominant Mask Regions], SaltMaskMinorityRegion [Minority Mask Regions], SaltMaskArbitaryRegion [Arbitrary Mask Regions], SaltMaskSmoothRegion [Smooth Mask Regions], SaltMaskErodeRegion [Erode Mask Regions], SaltMaskSubtract [Subtract Mask Regions], SaltMaskAdd [Add Mask Regions], SaltMaskInvert [Invert Mask Regions], SaltMaskDilateRegion [Dilate Mask Regions], SaltMaskFillRegion [Fill Mask Regions], SaltMaskThresholdRegion [Threshold Mask Regions], SaltMaskFloorRegion [Floor Mask Regions], SaltMaskCeilingRegion [Ceiling Mask Regions], SaltMaskGaussianRegion [Gaussian Mask Regions], SaltMaskEdgeDetection [Edge Detect Mask Regions], SaltMaskGradientRegion [Gradient Filter Mask Regions], SaltMaskAdaptiveThresholdingRegion [Adaptive Threshold Mask Regions], SaltMaskHistogramEqualizationRegion [Hisogram Equalize Mask Regions], SaltMaskRegionLabeling [Label Mask Regions (RGB)], SaltMaskContourExtraction [Countour Mask Regions Extraction], SaltMaskBilateralFilter [Bilateral Filter Mask Regions], SaltMaskClipHardeningFilter [Clip Harden Region], SaltMaskSharpeningFilter [Sharpen Mask Regions], SaltMaskSkeletonization [Skeletonize Mask Regions], SaltMaskNoiseAddition [Add Noise to Mask Regions], SaltMaskRegionSplit [Split Regions], SAIStringRegexSearchReplace [Regex Search and Replace], SAIStringRegexSearchMatch [Regex Search and Match], SAIPrimitiveConverter [Primitive Value Converter], SaltDisplayAny [SaltDisplayAny]

Added LoRa extension format: .results
Traceback (most recent call last):
  File "D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI_Language_Toolkit\modules\node_importer.py", line 22, in import_module
    module = importlib.import_module(module_name, package=package_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI_Language_Toolkit\nodes\autogen\__init__.py", line 1, in <module>
    from .agents import (
  File "D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI_Language_Toolkit\nodes\autogen\agents.py", line 1, in <module>
    from autogen import ConversableAgent
  File "D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\autogen\__init__.py", line 3, in <module>
    from .agentchat import *
  File "D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\autogen\agentchat\__init__.py", line 2, in <module>
    from .assistant_agent import AssistantAgent
  File "D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\autogen\agentchat\assistant_agent.py", line 5, in <module>
    from .conversable_agent import ConversableAgent
  File "D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 19, in <module>
    from ..code_utils import (
  File "D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\autogen\code_utils.py", line 9, in <module>
    import venv
ModuleNotFoundError: No module named 'venv'
Traceback (most recent call last):
  File "D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI_Language_Toolkit\modules\node_importer.py", line 22, in import_module
    module = importlib.import_module(module_name, package=package_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Projects\ImgGen\Interface\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SaltAI_Language_Toolkit\nodes\readers.py", line 75, in <module>
    from llama_index.readers.web import (
ModuleNotFoundError: No module named 'llama_index.readers.web'
```

**Comment by WAS-PlaiLabs** [comment]
Be sure to use the requirements file provided, with pinned versions that work with the current implementation.  For example we use web package `0.1.13` *not* `0.1.23`. Same for core (we use `0.10.36`), and other sensitive packages. Llama-Index is changing quickly and doesn't go through proper deprecation phases and things just sorta change from one version to another.
